@startuml
skinparam classAttributeIconSize 0



class ChessGUI #LightBlue {
    ..
}

class CreditsDialog #MistyRose {
    ..
}

class ChessBoard #LightGreen {
    ..
}

class ChessPiece #LightYellow {
    ..
}

class CheckerPiece #Wheat {
    ..
}

enum PieceType #LightGray {
    ..
}

enum PieceColor #Thistle {
    ..
}

class BattleshipGame #lightskyblue {
    ..
}

class Cell #LightYellow {
    ..
}

class Ship #Coral {
    ..
}

enum ShipType #LightPink {
    ..
}

class TicTacToe #plum {
    ..
}

class Cross_Circle #Brown {
    ..
}

ChessGUI  <-- "opens" ChessBoard
ChessGUI  <-- "opens"  CreditsDialog
ChessGUI  <-- "opens"  BattleshipGame
ChessGUI  <-- "opens"  TicTacToe
ChessBoard "1" <-- "0..32" ChessPiece
ChessBoard "1" <-- "0..24" CheckerPiece
ChessPiece "1" -- "1" PieceType
ChessPiece "1" -- "1" PieceColor
CheckerPiece "1" -- "1" PieceColor
BattleshipGame "1" <-- "100" Cell : playerBoard
BattleshipGame  "1"  <-- "100" Cell : enemyBoard
BattleshipGame "1" <-- "4" Ship
Ship "1" -- "1" ShipType
TicTacToe  <-- "moves" Cross_Circle
@enduml
